import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header/Header";
import Promotion from "../components/features bottom/promotion"
import Footer from "../components/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Awesome products designed by independent artists | Redbubble",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: 0 }}>
        <Header />
        {children}
        <Promotion/>
        <Footer/>
      </body>
    </html>
  );
}
